version: '3.8'

services:
  agent_api:
    build:
      context: ./agent/agent_api
    env_file: .env
    restart: unless-stopped
    depends_on:
      - influxdb

  agent_sites:
    build:
      context: ./agent/agent_sites
    env_file: .env
    restart: unless-stopped
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    env_file: .env
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      ### setup automático do InfluxDB v2
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3001:3000"
    environment:
      - GF_PROVISIONING_DATASOURCES_PATH=/etc/grafana/provisioning/datasources
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - GF_INSTALL_PLUGINS=grafana-influxdb-flux-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data: