apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    database: "${INFLUXDB_BUCKET}"
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: "10s"
      httpMode: "GET"
      version: "Flux"
      organization: "${INFLUXDB_ORG}"
    secureJsonData:
      token: "${INFLUXDB_TOKEN}"